theme: jekyll-theme-minimal
title: An Evolutionary View on Audience Perception of Good Films
description: What Influence Perceived Film Quality & How They Changed Over Time
show_downloads: True
navigation:
  - title: Home
    url: /
